### ISSUE TITLE
采用LSPatch修补无法正常生效

### ISSUE THREAD

**Issue by ZWolken** [zxy19/cjluFree#2]
使用LSPatch对Wecom进行修补操作后，软件初启动的部件加载部分进度会直接溢出，详见附图。
在50000%附近后将闪退，重新进入以及清除数据后重新进入均闪退。
有可能是非原生系统的锅，后续会尝试原生系统。
暂不考虑使用LSPosed（非备用机不考虑Magisk）
若懒得修复直接close这个issue as not planned就好（我不会介意的（大雾

系统: Android 12(Color OS 12.1)
型号: LE2100

附图: ![Screenshot_2022-08-05-16-54-11-94_5b9ffa3eca6ceb7](https://user-images.githubusercontent.com/76812845/183042874-03fdf166-873a-41dd-a3c1-7a26b150c51f.jpg)

**Comment by zxy19** [comment]
请禁用模块后启动企业微信重试，如果禁用模块后问题任然存在，麻烦提供下企业微信版本和lspatch版本方便调试，如果到时候能帮忙提供某些日志就更感激不尽了。

第一次用issue功能误操作了一下请不要介意（逃

**Comment by ZWolken** [comment]
后续已经发现问题所在并解决了，相关方法我这边复刻(fork)了您的仓库并描述了LSPatch修补模式的使用方法，除了系统相关操作无效其他都能正常使用，您可查看我这边[复刻的仓库](https://github.com/ZWolken/cjluFree)，我这边就把议题(issue)给关闭了（？
感恩感激.jpg

**Comment by ZWolken** [comment]
来个成功案例（
https://user-images.githubusercontent.com/76812845/183259239-1c81bfd2-b55b-4b37-84d0-37ed41178867.mp4

**Comment by zxy19** [comment]
你已经解决了就好。顺带其实我也是无root/xp环境（harmonyos）所以其实对各种奇怪的功能很多都留了非root实现的，比如shizuku就是单纯用于开关wifi的（逃）

**Comment by ZWolken** [comment]
睡好晚 ~~（我也是~~
那完全可以用我用的这种LSPatch方案嘛（
大佬可以看看我这边写的操作步骤（？
~~顺便花了点时间完善了仓库的issue~~
